// src/config/desiredDataPointsConfig.ts

import { DataPoint } from './dataPoints'; // Adjust path as needed

export interface SearchCriteria {
  nodeId?: string; // Keep for rare cases where a super-specific override is needed
  keywords: (string | RegExp)[];
  dataType?: DataPoint['dataType'];
  unit?: string;
  category?: DataPoint['category'] | DataPoint['category'][];
  phase?: string | 'any';
  limit?: number;
  descriptionHint?: string;
  // Optional: Boost score if uiType matches (e.g., we prefer 'display' or 'gauge' for readings)
  preferredUiTypes?: DataPoint['uiType'][];
}

export interface DesiredDataPointConfigEntry {
  id: string;
  criteria: SearchCriteria;
  isMultiPhaseGroup?: boolean;
}

export const desiredDataPointsConfig: DesiredDataPointConfigEntry[] = [
  // 1. Conceptual "System On/Off Status" (was previously hinted by ns=4;i=104)
  {
    id: 'systemOnOffStatus',
    criteria: {
      keywords: [
        /(^on$|off|run|stop|system|power).*(status|state)/i, // "on status", "system state", "power status"
        /on-off-status/i, // Common id pattern
        /run-state/i,
      ],
      dataType: 'Boolean', // Often a boolean, but could be Int16 (0/1)
      category: 'status',
      preferredUiTypes: ['display', 'switch'], // A switch might also represent this
      limit: 1,
      descriptionHint: 'The main on/off or operational status of the system.',
    },
  },

  // 2. Grid Voltage (all phases)
  {
    id: 'gridPhaseVoltages',
    criteria: {
      keywords: [
        /grid/i,
        /\bvoltage\b/i, // Whole word voltage
        /phase\s*[abc]/i,
        /L[123]/i,
        /(?<!limit|setting|config|upper|lower|max|min)\bvoltage\b/i, // Actual voltage, not a setting/limit for it
      ],
      unit: 'V',
      category: ['three-phase', 'grid'],
      phase: 'any',
      limit: 3,
      preferredUiTypes: ['display', 'gauge'],
      descriptionHint: 'Actual grid voltage measurements for each phase.',
    },
    isMultiPhaseGroup: true,
  },

  // 2. Inverter Output Phase Voltage (all phases)
  {
    id: 'inverterOutputPhaseVoltages',
    criteria: {
      keywords: [
        /inverter/i, /output/i, /\bvoltage\b/i, /phase\s*[abc]/i, /L[123]/i,
        /(?<!limit|setting|config|upper|lower|max|min)\bvoltage\b/i,
      ],
      unit: 'V',
      category: ['three-phase', 'inverter'],
      phase: 'any', // This signals the loop in useDynamicDefaultDataPointIds
      limit: 3,     // Crucial for getting A, B, and C if they exist
      preferredUiTypes: ['display', 'gauge'],
      descriptionHint: 'Inverter output voltage measurements for each phase.',
    },
    isMultiPhaseGroup: true,
  },
  // 3. Load Phase Power
  {
    id: 'loadPhasePowers',
    criteria: {
      keywords: [
        /\bload\b/i, // Whole word load
        /\bpower\b/i,
        /(W|watt)/i,
        /phase\s*[abc]/i,
        /L[123]/i,
        /(?<!limit|setting|config|max|min)\bpower\b/i,
      ],
      unit: 'W',
      category: ['three-phase', 'grid', 'energy'], // Load is consumption
      phase: 'any',
      limit: 3,
      preferredUiTypes: ['display', 'gauge'],
      descriptionHint: 'Power consumed by the load on each phase.',
    },
    isMultiPhaseGroup: true,
  },

  // 3. Inverter Output Phase Power
  {
    id: 'inverterOutputPhasePowers',
    criteria: {
      keywords: [
        /inverter/i,
        /output/i,
        /\bpower\b/i,
        /(W|watt)/i,
        /phase\s*[abc]/i,
        /L[123]/i,
        /(?<!limit|setting|config|max|min)\bpower\b/i,
      ],
      unit: 'W',
      category: ['three-phase', 'inverter'],
      phase: 'any',
      limit: 3,
      preferredUiTypes: ['display', 'gauge'],
      descriptionHint: 'Power generated by the inverter on each phase.',
    },
    isMultiPhaseGroup: true,
  },

  // 4. L1 Phase Frequency (Grid)
  {
    id: 'gridL1Frequency',
    criteria: {
      keywords: [
        /grid/i,
        /\bfrequency\b/i,
        /(L1|phase\s*a)/i, // Specific to L1 or Phase A
        /(?<!limit|setting|config|upper|lower|max|min)\bfrequency\b/i,
      ],
      unit: 'Hz',
      category: ['three-phase', 'grid'],
      phase: 'a',
      limit: 1,
      preferredUiTypes: ['display', 'gauge'],
      descriptionHint: 'Grid frequency measured on Phase L1/A.',
    },
  },

  // 5. Conceptual "Battery Voltage" (was previously hinted by ns=4;i=114)
  // {
  //   id: 'batteryVoltage',
  //   criteria: {
  //     // nodeId: 'ns=4;i=114', // REMOVED for broader matching
  //     keywords: [
  //         /\bbattery\b/i,
  //         /\bvoltage\b/i,
  //         /(?<!limit|setting|config|upper|lower|max|min|empty)\bvoltage\b/i, // Avoid "battery voltage setting"
  //         /bat-v/i, // common id pattern
  //       ],
  //     dataType: 'Int16', // This is a hint, but could be Float too
  //     unit: 'V',
  //     category: 'battery',
  //     limit: 1,
  //     preferredUiTypes: ['display', 'gauge'],
  //     descriptionHint: 'Current battery voltage reading.',
  //   },
  // },

//   // ---- Other "Critical" data points (from your original example getDefaultDataPointIds) ---
//   // We'll define them conceptually
//   {
//     id: 'gridTotalActivePower',
//     criteria: {
//         keywords: [/grid/i, /total/i, /(active\s*)?power/i, /side-to-side/i, /grid.*power/i],
//         unit: 'W',
//         category: 'grid',
//         phase: 'x', // 'x' for total/non-phase-specific
//         preferredUiTypes: ['display', 'gauge'],
//         limit: 1,
//         descriptionHint: "Total active power from/to the grid."
//     }
//   },
//   {
//     id: 'inverterTotalOutputPower',
//     criteria: {
//         keywords: [/inverter/i, /output/i, /total/i, /(active\s*)?power/i],
//         unit: 'W',
//         category: 'inverter',
//         phase: 'x',
//         preferredUiTypes: ['display', 'gauge'],
//         limit: 1,
//         descriptionHint: "Total power output from the inverter."
//     }
//   },
//   {
//     id: 'loadTotalPower',
//     criteria: {
//         keywords: [/load/i, /total/i, /(active\s*)?power/i],
//         unit: 'W',
//         category: ['grid', 'energy'], // Load can be related to grid or just energy consumption
//         phase: 'x',
//         preferredUiTypes: ['display', 'gauge'],
//         limit: 1,
//         descriptionHint: "Total power consumed by the load."
//     }
//   },
//   {
//     id: 'batteryCapacitySoC', // Kept this one as it was good
//     criteria: {
//       keywords: [/\bbattery\b/i, /(capacity|soc|state of charge)/i, /(?<!setting|limit)\b(capacity|soc)/i],
//       unit: '%',
//       category: 'battery',
//       preferredUiTypes: ['display', 'gauge'],
//       limit: 1,
//       descriptionHint: "Battery's current state of charge.",
//     },
//   },
//   {
//     id: 'batteryOutputPower',
//     criteria: {
//         keywords: [/\bbattery\b/i, /(output|discharge|charge).*power/i, /\bpower\b/i, /(?<!setting)\bpower\b/i],
//         unit: 'W',
//         category: 'battery',
//         phase: 'x',
//         preferredUiTypes: ['display', 'gauge'],
//         limit: 1,
//         descriptionHint: "Current power from/to the battery (positive for discharge, negative for charge)."
//     }
//   },
//   {
//     id: 'pvInputPower', // Try to get total or PV1 if total is not distinct
//     criteria: {
//       keywords: [/pv/i, /solar/i, /input/i, /(total\s*)?power/i, /pv1/i, /(?<!setting)\bpower\b/i],
//       unit: 'W',
//       category: 'pv',
//       phase: 'x', // Or allow searching specific PV strings if preferred
//       preferredUiTypes: ['display', 'gauge'],
//       limit: 1, // We want the most representative one (e.g., total, or PV1)
//       descriptionHint: 'Power generated by PV arrays, ideally total or PV1.',
//     },
//   },
];